load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_binary(
    name = "hello",
    srcs = [
        "hello.scala",
    ],
    main_class = "hello"
)

scala_binary(
    name = "hello2",
    srcs = [
        "hello2.scala",
    ],
    main_class = "hello2"
)

scala_binary(
    name = "hello3",
    srcs = [
        "hello3.scala",
    ],
    main_class = "hello3"
)

scala_binary(
    name = "helloyou",
    srcs = [
        "helloyou.scala",
    ],
    main_class = "helloyou"
)
